@startuml
enum it.polimi.ingsw.Enum.Color {
+  GREEN
+  YELLOW
+  BLUE
+  LIGHTBLUE
+  PINK
+  WHITE
}
enum it.polimi.ingsw.Enum.EchoID {
+  PANIC
+  NOID
+  GAMEFULL
+  BADNICK
+  BADCOLUMN
+  NICKOK
+  JOINED
+  CREATED
+  GAMESTARTED
+  WRONG_CHOSEN_TABLE_INDEX
+  WRONGSTATE
+  NOTACTIVE
+  BADPICKUP
+  COLUMNDIFF
+  NOPLAYER
+  LAST_TURN
}
enum it.polimi.ingsw.Enum.GameState {
+  PREGAME
+  PICK_UP_TILES
+  INSERT_TILES
+  END
}
@enduml