@startuml
class it.polimi.ingsw.model.EndOfTurn.BoardRefresher.RefreshTrigger {
+ {static} boolean isBoardRefreshable(Board)
- {static} boolean isNotNull(ItemTile)
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.FourAnglesCGS {
+ boolean isGoalAchieved(Shelf)
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.FourGroupsOfFourCGS {
+ boolean isGoalAchieved(Shelf)
}
class it.polimi.ingsw.model.EndOfTurn.ScoreCalculation.AdjacencyScoreCalculation {
+ {static} int calculateScore(Player)
- {static} List<Integer> findClusters(ItemTile[][])
- {static} List<Integer> dfs(ItemTile[][],int,int,Color,Set<String>)
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.XShapedCGS {
+ boolean isGoalAchieved(Shelf)
}
class it.polimi.ingsw.model.cards.personalGoals.PersonalCardDealer {
- {static} File personalCardsDirectory
+ {static} void getCards(ArrayList<Player>)
}
class it.polimi.ingsw.model.EndOfTurn.BoardRefresher.BoardRefresher {
- Board board
- Bag BAG
- Game GAME
- boolean[][] lookUpTable
+ void refillBoard()
+ void update()
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.ScaleCGS {
+ boolean isGoalAchieved(Shelf)
+ boolean hasIncreasingColumns(ItemTile[][],boolean)
}
class it.polimi.ingsw.model.cards.commonGoals.CommonGoalCard {
- ArrayList<VirtualViewObserver> observers
# Stack<Integer> pointsStack
- CommonGoalStrategy commonGoalStrategy
- HashSet<Player> playersWhoCompleted
- void initStackPoints()
+ int calculateScore(Player)
+ boolean hasCompleted(Player)
- boolean isGoalAchieved(Shelf)
+ int popPoints()
+ int peekPoints()
+ String getCardName()
+ void registerObserver(VirtualViewObserver)
+ void removeObserver(VirtualViewObserver)
+ void notifyObservers()
}
class it.polimi.ingsw.model.Game {
- ArrayList<VirtualViewObserver> observers
- int BOARD_DIMENSION
- int MAX_PLAYER_NUMBER
- VirtualView virtualView
- int gameID
- Bag bag
- Board board
- ChosenTilesTable chosenTilesTable
- GameState gameState
- ArrayList<CommonGoalCard> commonGoals
- ArrayList<Player> players
- Player activePlayer
- TurnHandler turnHandler
+ ArrayList<CommonGoalCard> getCommonGoals()
+ void start()
+ void setVirtualView(VirtualView)
- void turnHandlerInitializer()
+ void end()
+ Board getBoard()
+ ArrayList<Player> getPlayers()
+ Player getActivePlayer()
+ void setActivePlayer(Player)
+ Bag getBag()
+ void setBoard(Board)
+ int getMAX_TILES_FROM_BOARD()
+ ChosenTilesTable getChosenTilesTable()
+ void addPlayer(Player)
+ TurnHandler getTurnHandler()
+ Player getWinner()
+ int getMAX_PLAYER_NUMBER()
+ void setGameID(int)
+ int getGameID()
+ void setGameState(GameState)
+ Player getPlayer(String)
+ void disconnectPlayer(String)
+ GameState getGameState()
+ VirtualView getVirtualView()
+ void registerObserver(VirtualViewObserver)
+ void removeObserver(VirtualViewObserver)
+ void notifyObservers()
}
interface it.polimi.ingsw.model.EndOfTurn.EndOfTurnSubject {
~ void attachEndOfTurn(EndOfTurnObserver)
~ void notifyObservers()
}
class it.polimi.ingsw.model.EndOfTurn.TurnHandler {
+ Game game
- List<EndOfTurnObserver> observers
- List<Player> players
- boolean lastTurn
+ void changeTurn()
+ boolean isLastTurn()
+ void startLastTurn()
+ void attachEndOfTurn(EndOfTurnObserver)
+ void notifyObservers()
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.FourRowsOfFiveCGS {
+ boolean isGoalAchieved(Shelf)
- boolean hasLessThanFiveTiles(ItemTile[])
}
class it.polimi.ingsw.model.player.Shelf {
- ArrayList<VirtualViewObserver> observers
- int COLUMNS
- int ROWS
- ItemTile[][] shelfGrid
+ ItemTile getTileAtLocation(Point)
+ void setTileAtLocation(Point,ItemTile)
+ void setShelfGrid(ItemTile[][])
+ ItemTile[][] getShelfGrid()
+ int getNumOfBoxLeftInCol(int)
+ boolean isColumnFull(int)
+ int getCOLUMNS()
+ int getROWS()
+ boolean insertTile(ItemTile,int)
+ boolean isFull()
+ void registerObserver(VirtualViewObserver)
+ void removeObserver(VirtualViewObserver)
+ void notifyObservers()
}
class it.polimi.ingsw.model.tiles.ItemTile {
- Color COLOR
- int id
+ int getId()
+ Color getColor()
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.SixGroupsOfTwoCGS {
+ boolean isGoalAchieved(Shelf)
}
class it.polimi.ingsw.model.board.Board {
- ArrayList<VirtualViewObserver> OBSERVERS
- ItemTile[][] BOARD_GRID
+ ItemTile[][] getBoardGrid()
+ int getSize()
+ void setItemTile(Color,int,int)
+ ItemTile removeItemTile(Point)
+ ArrayList<ItemTile> removeItemTiles(ArrayList<Point>)
+ void emptyBoard()
+ void registerObserver(VirtualViewObserver)
+ void removeObserver(VirtualViewObserver)
+ void notifyObservers()
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.ThreeMaxThreeDiffCGS {
+ boolean isGoalAchieved(Shelf)
}
class it.polimi.ingsw.model.player.ShelfUtils {
+ {static} boolean checkMatrixWithDFS(ItemTile[][],int,int)
- {static} int dfs(ItemTile[][],boolean[][],int,int,Color)
}
interface it.polimi.ingsw.model.EndOfTurn.EndOfTurnObserver {
~ void update()
}
class it.polimi.ingsw.model.tiles.Bag {
- int NUMBER_OF_COLORS
- int TILES_PER_COLOR
- int tilesLeft
- HashMap<Color,Integer> colorNumber
+ ItemTile drawTile()
~ Color randomColor()
}
class it.polimi.ingsw.model.cards.commonGoals.CommonCardDealer {
+ {static} List<CommonGoalStrategy> possibleCommonGoals
+ {static} List<CommonGoalStrategy> pickCardStrategies(int)
+ {static} List<CommonGoalCard> pickCommonGoalCards(int)
- {static} void initCommonGoals()
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.FiveTilesDiagonalCGS {
+ boolean isGoalAchieved(Shelf)
}
class it.polimi.ingsw.model.board.ChosenTilesTable.ChosenTilesTable {
- List<VirtualViewObserver> observers
- List<ItemTile> chosenTiles
- Board board
- Integer chosenColumn
+ void addTiles(ArrayList<ItemTile>)
+ ItemTile popTile(int)
+ ItemTile getTile(int)
+ int size()
+ Integer getChosenColumn()
+ void setChosenColumn(Integer)
+ List<ItemTile> getChosenTiles()
+ void registerObserver(VirtualViewObserver)
+ void removeObserver(VirtualViewObserver)
+ void notifyObservers()
}
abstract class it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy {
~ CommonGoalReader reader
+ {abstract}boolean isGoalAchieved(Shelf)
+ String getCardName()
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.TwoSquaresCGS {
+ boolean isGoalAchieved(Shelf)
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.TwoRowsWithFiveDiffCGS {
+ boolean isGoalAchieved(Shelf)
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.TwoColSixDiffCGS {
+ boolean isGoalAchieved(Shelf)
}
class it.polimi.ingsw.model.EndOfTurn.ScoreCalculation.ScoreBoard {
- Game game
- boolean isFirstPointAssigned
- ArrayList<CommonGoalCard> commonGoals
- void scoreCommonGoalCards(Player)
+ void update()
- Player getPreviousActivePlayer()
+ void endGameScoreUpdate()
- void scoreFirstCompletedShelf(Player)
- void scorePersonalGoals()
- void scoreAdjacency()
}
class it.polimi.ingsw.model.player.Player {
- ArrayList<VirtualViewObserver> observers
- Shelf shelf
- PersonalGoal personalGoal
- String nickname
- boolean isConnected
- int score
+ int getScore()
+ Shelf getShelf()
+ PersonalGoal getPersonalGoal()
+ void setPersonalGoal(PersonalGoal)
+ String getNickname()
+ void updateScore(int)
+ void setConnected(boolean)
+ boolean isConnected()
+ void registerObserver(VirtualViewObserver)
+ void removeObserver(VirtualViewObserver)
+ void notifyObservers()
}
class it.polimi.ingsw.model.cards.personalGoals.PersonalGoal {
- HashMap<Color,Point> achievements
- Player player
- Stack<Integer> points
- String cardNumber
+ int calculateScore()
- int getPoints()
+ HashMap<Color,Point> getAchievements()
+ Stack<Integer> getPointStack()
+ String getCardNumber()
}
class it.polimi.ingsw.model.board.ChosenTilesTable.PickUpValidator {
+ {static} boolean isValid(Game,ArrayList<Point>)
- {static} boolean onSameLine(ArrayList<Point>)
- {static} boolean adjacent(ArrayList<Point>)
- {static} boolean hasFreeAdjacentNeighbor(ItemTile[][],Point)
- {static} boolean tooManyTilesChosen(Game,int)
}
class it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.EightTilesSameColorCGS {
+ boolean isGoalAchieved(Shelf)
}


it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.FourAnglesCGS
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.FourGroupsOfFourCGS
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.XShapedCGS
it.polimi.ingsw.model.EndOfTurn.EndOfTurnObserver <|.. it.polimi.ingsw.model.EndOfTurn.BoardRefresher.BoardRefresher
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.ScaleCGS
it.polimi.ingsw.VirtualView.ModelObservers.VirtualViewSubject <|.. it.polimi.ingsw.model.cards.commonGoals.CommonGoalCard
it.polimi.ingsw.VirtualView.ModelObservers.VirtualViewSubject <|.. it.polimi.ingsw.model.Game
it.polimi.ingsw.model.EndOfTurn.EndOfTurnSubject <|.. it.polimi.ingsw.model.EndOfTurn.TurnHandler
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.FourRowsOfFiveCGS
it.polimi.ingsw.VirtualView.ModelObservers.VirtualViewSubject <|.. it.polimi.ingsw.model.player.Shelf
java.io.Serializable <|.. it.polimi.ingsw.model.tiles.ItemTile
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.SixGroupsOfTwoCGS
it.polimi.ingsw.VirtualView.ModelObservers.VirtualViewSubject <|.. it.polimi.ingsw.model.board.Board
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.ThreeMaxThreeDiffCGS
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.FiveTilesDiagonalCGS
it.polimi.ingsw.VirtualView.ModelObservers.VirtualViewSubject <|.. it.polimi.ingsw.model.board.ChosenTilesTable.ChosenTilesTable
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.TwoSquaresCGS
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.TwoRowsWithFiveDiffCGS
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.TwoColSixDiffCGS
it.polimi.ingsw.model.EndOfTurn.EndOfTurnObserver <|.. it.polimi.ingsw.model.EndOfTurn.ScoreCalculation.ScoreBoard
it.polimi.ingsw.VirtualView.ModelObservers.VirtualViewSubject <|.. it.polimi.ingsw.model.player.Player
it.polimi.ingsw.model.cards.commonGoals.CommonGoalStrategy <|-- it.polimi.ingsw.model.cards.commonGoals.commonGoalsStrategy.EightTilesSameColorCGS
@enduml